services:
  # API
  gsa-api:
    image: ntnp/laravel-dev:8.4
    container_name: gsa-api
    hostname: gsa-api
    depends_on:
      - gsa-mysql
      - gsa-redis
    networks:
      - app
    ports:
      - "5173:5173"
    volumes:
      - ./gsa-api:/var/www/html

  # API Horizon/Scheduler
  gsa-api-horizon:
    image: ntnp/laravel-horizon-dev:8.4
    container_name: gsa-api-horizon
    hostname: gsa-api-horizon
    depends_on:
      - gsa-mysql
      - gsa-redis
    networks:
      - app
    volumes:
      - ./gsa-api:/var/www/html

  # API Reverb
  gsa-api-reverb:
    image: ntnp/laravel-reverb-dev:8.4
    container_name: gsa-api-reverb
    hostname: gsa-api-reverb
    depends_on:
      - gsa-mysql
      - gsa-redis
    networks:
      - app
    volumes:
      - ./gsa-api:/var/www/html

  # API web
  gsa-api-web:
    image: nginx:latest
    container_name: gsa-api-web
    hostname: gsa-api-web
    depends_on:
      - gsa-api
    networks:
      - app
    ports:
      - "8070:80"
      - "8071:443"
    volumes:
      - ./gsa-api:/var/www/html
      - ./.docker/nginx/ssl:/etc/nginx/ssl
      - ./.docker/nginx/api-web.conf:/etc/nginx/conf.d/default.conf

  # API Reverb web
  gsa-api-reverb-web:
    image: nginx:latest
    container_name: gsa-api-reverb-web
    hostname: gsa-api-reverb-web
    depends_on:
      - gsa-api-reverb
    networks:
      - app
    ports:
      - "9070:80"
      - "9071:443"
    volumes:
      - ./gsa-api:/var/www/html
      - ./.docker/nginx/ssl:/etc/nginx/ssl
      - ./.docker/nginx/api-reverb-web.conf:/etc/nginx/conf.d/default.conf

  # MySQL
  gsa-mysql:
    image: mariadb:latest
    container_name: gsa-mysql
    hostname: gsa-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 20250101
    networks:
      - app
    ports:
      - "3370:3306"
    volumes:
      - ./.docker_data/mysql:/var/lib/mysql

  # Redis
  gsa-redis:
    image: redis:alpine
    container_name: gsa-redis
    hostname: gsa-redis
    command: "redis-server --requirepass 20250101"
    networks:
      - app
    ports:
      - "6370:6379"

networks:
  app:
    driver: bridge
