services:
  # API
  gs-api:
    image: ntnp/laravel-dev:8.4
    container_name: gs-api
    hostname: gs-api
    depends_on:
      - gs-mysql
      - gs-redis
    networks:
      - app
    ports:
      - "5173:5173"
    volumes:
      - ./gs-api:/var/www/html

  # API Horizon/Scheduler
  gs-api-horizon:
    image: ntnp/laravel-horizon-dev:8.4
    container_name: gs-api-horizon
    hostname: gs-api-horizon
    depends_on:
      - gs-mysql
      - gs-redis
    networks:
      - app
    volumes:
      - ./gs-api:/var/www/html

  # API Reverb
  gs-api-reverb:
    image: ntnp/laravel-reverb-dev:8.4
    container_name: gs-api-reverb
    hostname: gs-api-reverb
    depends_on:
      - gs-mysql
      - gs-redis
    networks:
      - app
    volumes:
      - ./gs-api:/var/www/html

  # API web
  gs-api-web:
    image: nginx:latest
    container_name: gs-api-web
    hostname: gs-api-web
    depends_on:
      - gs-api
    networks:
      - app
    ports:
      - "8070:80"
      - "8071:443"
    volumes:
      - ./gs-api:/var/www/html
      - ./.docker/nginx/ssl:/etc/nginx/ssl
      - ./.docker/nginx/api-web.conf:/etc/nginx/conf.d/default.conf

  # API Reverb web
  gs-api-reverb-web:
    image: nginx:latest
    container_name: gs-api-reverb-web
    hostname: gs-api-reverb-web
    depends_on:
      - gs-api-reverb
    networks:
      - app
    ports:
      - "9070:80"
      - "9071:443"
    volumes:
      - ./gs-api:/var/www/html
      - ./.docker/nginx/ssl:/etc/nginx/ssl
      - ./.docker/nginx/api-reverb-web.conf:/etc/nginx/conf.d/default.conf

  # MySQL
  gs-mysql:
    image: mariadb:latest
    container_name: gs-mysql
    hostname: gs-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 20240101
    networks:
      - app
    ports:
      - "3370:3306"
    volumes:
      - ./.docker_data/mysql:/var/lib/mysql

  # Redis
  gs-redis:
    image: redis:alpine
    container_name: gs-redis
    hostname: gs-redis
    command: "redis-server --requirepass 20240101"
    networks:
      - app
    ports:
      - "6370:6379"

networks:
  app:
    driver: bridge
